sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bsobbe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bsobbe/docker-react npm run test

deploy:
  provider: s3
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-216092014724"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS
  secret_access_key:
    secure: $AWS_SECRET